### ISSUE TITLE
Longitudes need to be multiplied by -1

### ISSUE THREAD

**Issue by bglong11** [BigelowLab/maree#1]
(1) When I import into  a GIS (ArcGIS Pro) the longitudes are not correct and need to be multiplied by -1. Latitudes are correct.  
(2) Can you extend this very useful tool to include all stations and not just US?
Thanks! 
Brian
(I am new to github so please bear with me if I am not doing this correctly).
![Screenshot 2023-04-05 051026](https://user-images.githubusercontent.com/19760730/229979004-b8db3893-34b8-46ac-a655-cad9b2f806ff.png)

**Comment by btupper** [comment]
Hi Brian,

Welcome to git and github.  

1.  Please provide a **small** example that demonstrates how you generated the output.  It should be something that I can copy and paste to run on my own computer.  Check out the [reprex](https://www.tidyverse.org/help/) package for help on that.  That said, see note 2.

2. maree is a wrapper around xtide - xtide provides all of the computation and data tables needed for maree.  See the [xtide](https://flaterco.com/xtide/) website and its [FAQs](https://flaterco.com/xtide/faq.html#60) if you want to extend its usage. 

Cheers,
Ben

**Comment by bglong11** [comment]
Hi Ben,
Thanks for the quick response!
The earlier email showed a screen capture of ArcGIS Pro map after adding the csv. 
To do this I added the csv to ArcGIS Pro and displayed xy data.  
I will follow up on your note 2. 
Cheers,

Brian

Below is R code:

library(maree)
locs <- fetch_locations()
view(locs)
write.csv(locs, "XTide.csv")

Below is the first few lines of XTides.csv:

"","Station ID","Name","Type","Latitude","Longitude"
"1","CHB9904_9","0.15 nmi WSW of Pier No. 2 (depth 15 ft), Newport News, Hampton Roads, Virginia Current","Ref",36.9792,76.4435
"2","CHB9904_5","0.15 nmi WSW of Pier No. 2 (depth 29 ft), Newport News, Hampton Roads, Virginia Current","Ref",36.9792,76.4435
"3","CHB9904_1","0.15 nmi WSW of Pier No. 2 (depth 42 ft), Newport News, Hampton Roads, Virginia Current","Ref",36.9792,76.4435
"4","CHB9904_12","0.15 nmi WSW of Pier No. 2 (depth 6 ft), Newport News, Hampton Roads, Virginia Current","Ref",36.9792,76.4435
"5","PCT3896_1","0.2 mi off Flat Point, Taku Inlet, Stephens Passage, Alaska Current","Sub",58.3333,134.05
"6","PCT3901_1","0.2 mi off Taku Point, Taku Inlet, Stephens Passage, Alaska Current","Sub",58.4,134.0167

**Comment by btupper** [comment]
Ah, the issue arises when I cast the 'W' multiplier from logical to numeric through multiplication.  Probably I shouldn't rely on automatic data type casting, but instead do it explicitly.  

https://github.com/BigelowLab/maree/blob/master/R/misc.R#L63

I'll try to fix that soon.  In the meantime, something you may be doing this already...

```
locs <- fetch_locations() |>
  mutate(Longitude = -1 * Longitude)
```

**Comment by btupper** [comment]
I have just pushed an update - can you test it out and then let me know what you think?

**Comment by bglong11** [comment]
Hi Ben,
Well done and thanks.
I went through the FAQ and it appears that stations outside the US are not
public domain.
I am interested in Indonesia so I guess I will not be able to use your
tools.
Cheers
Brian
Alternative email: ***@***.***

**Comment by btupper** [comment]
Ok - thanks for getting back to me.  

I'm not sure what to suggest for non-US databases, but this looks promising - http://uhslc.soest.hawaii.edu

I would be interested to learn how this goes. Best wishes, Ben
